README.md
Fixed version of https://github.com/jsalt18-sentence-repl/jiant/pull/406 based on @sleepinyourhat's comment there
=> added link to DNC in README.md

.gitmodules
=> Switch to HTTPS for public submodules

config/defaults.conf, src/models.py, src/modules.py, src/trainer.py
Some cosmetic changes (while testing other ideas)
* Adding/removing old arguments from docstrings
* Modifying default config to have the right name for classifier 
* Typos
=> Improve docs and cosmetic changes

src/utils.py
=> resolve variable naming TODO

probing/data/README.md, probing/data/convert-dpr.py, probing/data/convert-spr2.py, probing/data/extract_ontonotes_all.py, probing/data/get_dpr_data.sh, probing/data/get_spr2_data.sh
Cleaned up from `edgeprobe_docs` branch, and tested that everything works.
Refactored a number of scripts to have cleaner argument handling.
=> Edge probing data-prep scripts

src/preprocess.py, src/tasks/registry.py
Remove some parameter salad and nested-hell in preparation for updating tokenizer support.
=> Minor refactor of get_tasks

src/bert/utils.py
You want ones for the nonzero tokens :)
=> Critical bug: fix sign of BERT attention mask

scripts/edges/kubernetes_run_all.sh
Specify GPU type alone with the cluster so we don't need to run twice with different arguments.
=> Minor cleanup of edge probing runner script

environment.yml, src/evaluate.py, src/modules/modules.py, src/trainer.py, src/utils/utils.py
Upgrading to 1.0.0 and 0.8.1
Refer to #442  for notes. 
The last_dim_softmax in AllenNLP was merged into masked_softmax (See this PR: https://github.com/allenai/allennlp/pull/1687/files).
=> Pytorch and AllenNLP upgrade

src/utils/utils.py
Fixes a crash introduced by #476
=> Fix import of "device_mapping"

config/defaults.conf, scripts/edges/exp_fns.sh, scripts/edges/kubernetes_run_all.sh, src/openai_transformer_lm/utils.py
Follow-up for #480, add this to the GPT model so we can do an apples-to-apples comparison.
=> Add scalar mixing to OpenAI Transformer LM

scripts/edges/kubernetes_run_all.sh
Remove some experiments that we're not using.
=> Clean up Kubernetes script

scripts/edges/analyze_project.sh
=> Edge probing: analyze_project script

Dockerfile, gcp/kubernetes/run_batch.sh
New features, and support for some experimental stuff I'm working on.
Needed to start work on #491
=> Upgrade to latest pytorch_pretrained_bert package

cola_inference.py
=> Inference labeled data

cola_inference.py
=> Add additional columns to inference output

cola_inference.py
See: https://github.com/jsalt18-sentence-repl/jiant/pull/511#issuecomment-472040153
=> Recommit Inference/Label changes

src/modules/modules.py
Add first state "pooling" (i.e. take first hidden state of sequence). Relevant for BERT integration.
=> Add first state pooling

src/tasks/tasks.py
Fix bug in loading MNLI dev data
=> Fix data loading bug

config/defaults.conf, src/trainer.py
Includes:
* train for a maximum number of epochs (passes over all of a task's data)
* refactoring of stop check in trainer
* removal of a possible infinite loop bug
=> Trainer for a fixed number of epochs

src/tasks/tasks.py, src/utils/data_loaders.py
* in `load_tsv`, also check if sent2 has length 0
* `targ_idx` -> `label_idx`
* `idx_idx` -> `return_indices=True`
=> Fix dataloading issues with MNLI and load_tsv

src/trainer.py
Add an option to use the BERT optimizer, with and without a max number of epochs to train for.
=> Add BERT Adam support

src/models.py, src/modules/modules.py, src/tasks/tasks.py
Fixed update flow for STS-B scorer in src/models.py
=> Fixing STS-B Scorer 

main.py
Fix to allow runs reusing pretraining parameters for task specific modules.
=> Fixed task_names_to_avoid_loading bug

src/trainer.py
=> change log format

src/modules/seq2seq_decoder.py
deprecation warning added for seq2seq_decoder
=> decoder issue #566

config/defaults.conf, config/demo.conf, config/edgeprobe_demo.conf, main.py, src/trainer.py
Modified `main.py` and  train function in `src/trainer.py`
=> removed bpp_base and changed the n_batches_per_pass to 1 by default

src/models.py, src/modules/edge_probing.py, src/modules/modules.py
remaned sent_embs to word_embs_in_context
=> Cleanup: Rename sent_embs #580

README.md, config/defaults.conf, path_config.sh, src/preprocess.py
Remove fasttext model support, as per #523 . Delete relevant code and update documentation (removing paths and config options).
=> Remove fasttext model

main.py
Fix a check to look at the correct argument (`args.pretrain_tasks` -> `args.target_tasks`)
=> Fix target task check

src/tasks/tasks.py
- Ran WiC, verified runs correctly
- Ran demo.conf
=> Remove problematic detach

src/tasks/__init__.py
Add tasks to SuperGLUE task list in `src/tasks/__init__.py`
=> Add tasks to superglue task group

main.py, src/models.py, src/preprocess.py, src/trainer.py, src/utils/tokenizers.py, src/utils/utils.py
A few changes to try to make the logs a bit less bizarre in average use cases. They're still pretty bad.
Goes 5% of the way to addressing #602.
Nearly all of these changes are string edits only.
=> Log cleanup

scripts/download_glue_data.py
Two fixes:
- downloading "diagnostic" downloads both diagnostic files we use (one for MNLI and one for GLUEDiagnostic)
- when downloading MNLI, also download the diagnostic data
Addresses #495
=> Update downloader script to download both diagnostic files

scripts/download_superglue_data.py
=> Add SuperGLUE data download script

src/trainer.py
This is an awkward partial-fix, but it fixes everything that's visible in the logs, and I think it does more good than harm.
=> Add come some comments/clarafications on our use of 'epoch'

src/evaluate.py
We should write preds, not labels.
=> Fix bug in writing diagnostic preds

src/evaluate.py, src/tasks/qa.py
- fix a bug in computing exact match
- adjust prediction file format to match that of SuperGLUE server
- update some comments
=> MultiRC fixes

.circleci/config.yml, README.md, src/evaluate.py, src/tasks/qa.py, src/tasks/tasks.py
Adding black tests, black badge, and minor changes so current repo passes tests.
Test will fail if codebase does not pass black formatting check.
=> Black in CI

environment.yml
This should also fix the failing tests for the write_preds testing PR
=> Adding pyhocon

tutorials/setup_tutorial.md
=> update tutorial: git clone command

tutorials/setup_tutorial.md
=> Changed v0.9.0 -> 0.9.1 in tutorial

main.py
This seems to crash any time you specify multiple target tasks—the variable isn't defined anywhere. Here's a proposed local fix, but this seems like a clue that we need better test coverage for checkpointing.
=> Fix checkpoint name variable bug in main.py

main.py
=> Checkpoint pathfinding fix

src/tasks/tasks.py
=> Changing relative path for WSC

main.py
Removing some fragments of older versions of checkpointing in the evaluation, and modifying assert to ensure that ckpt is not None.
=> Cleaning up main.py target train 

main.py
=> Add a couple more warnings/asserts around checkpointing logic

config/defaults.conf, config/demo.conf, config/superglue-bow.conf
=> Cut out task-specific defaults

src/models.py, src/trainer.py, src/utils/config.py
Simplifies/exposes some tricky logic, and fixes #755.
=> Rewrite get_task_attr and build_trainer_params

.circleci/config.yml
Addresses #750. This is essentially an integration test for some of our checkpointing logic.
=> Add an eval-only run to CI

README.md
As requested in #620 . Some of the authors are working on the dataset issues, which will hopefully be resolved very soon.
=> Added link to the branch for function words paper

config/defaults.conf, config/superglue-bert.conf, src/models.py
=> Change classifier_loss_fn name, default

src/models.py
=> Fix fatal model-building bug

scripts/superglue-baselines.sh, src/tasks/tasks.py
Not adding in a warning as this is the first release of BoolQ in SuperGLUE.
=> Adjust to new BoolQ data (combined title and passage)

scripts/download_glue_data.py
=> Update path for QQP in glue downloader

config/defaults.conf, main.py, src/trainer.py, tests/test_checkpointing.py
Remove mentions of `shared_optimizer` (i.e. always use a single optimizer in multi task learning)
Addresses #597
=> Purge shared optimizer

src/tasks/qa.py
Some changes in MultiRC data format necessitates code changes:
- "isAnswer" -> "label"
- "paragraph" -> "passage"
- removed HTML from passage text
- check versioning
=> Update MultiRC to new data format

main.py, scripts/superglue-baselines.sh, src/tasks/qa.py
Previously would error out during test evaluation b/c we skipped loading test answers (because there aren't any). Now we load dummy answers.
=> Fix ReCoRD test evaluation

scripts/superglue-baselines.sh, src/tasks/tasks.py
Adds commands for the STILTS-style SuperGLUE baselines (BERT++ in the tables) and CBOW baselines. I could see an argument for separating the CBOW commands into a different script.
=> Add baselines

tutorials/setup_tutorial.md
The current method of downloading NLTK dependencies errored out.
=> Change instructions for NLTK for setup tutorial

.circleci/config.yml, scripts/winograd/preprocess_winograd.py
Caught some lingering `src` mentions and made them jiant.
=> Remove lingering src mentions

jiant/tasks/tasks.py, scripts/superglue-baselines.sh
- In `rte-bow` move Winogender to a target task
- Revert breaking `rte-superglue` data loading change
- Return something in Winogender `process_split`
- Change data file from `winogender_filtered.jsonl` -> `Winogender.jsonl` to match server download
=> Some fixes

jiant/tasks/qa.py, jiant/tasks/tasks.py
=> `dev.jsonl` -> `val.jsonl`

main.py
Check if task has use_classifier attribute before loading model during evaluation.
Addresses #829
=> Check if task has use_classifier attribute before loading model

README.md
Still need to make the 1.0 package and make a corresponding update to the site homepage (which probably also says WIP) and to the tutorial.
=> 1.0 to readme.

jiant/modules/span_modules.py, jiant/tasks/tasks.py
Allennlp F1Scorer expects a different input shape to 0.8.1 - updating that here for WSC.
=> AllenNLP F1_scorer update 

jiant/trainer.py
=> Make sure task-specific checkpoints are cleared when replaced

README.md
=> Contributor guidelines

gcp/config/auto.nfs
Old one pointed to a very old cloud set-up, replace with a reasonable default & helpful comment.
=> Fix NFS server path

jiant/trainer.py
Fixes https://github.com/nyu-mll/jiant/issues/889#issue-480832195.
One SuperGLUE val run looks as follows:
```
08/15 09:27:02 PM: macro_avg: validation: 0.336736
08/15 09:27:02 PM: micro_avg: validation: 0.243849
08/15 09:27:02 PM: boolq_acc_f1: training: 0.702770 validation: 0.693867
08/15 09:27:02 PM: boolq_accuracy: training: 0.633069 validation: 0.621407
08/15 09:27:02 PM: boolq_f1: training: 0.772472 validation: 0.766327
08/15 09:27:02 PM: boolq_precision: training: 0.638792 validation: 0.621746
08/15 09:27:02 PM: boolq_recall: training: 0.976909 validation: 0.998524
08/15 09:27:02 PM: commitbank_accuracy: training: 0.067661 validation: 0.089286
08/15 09:27:02 PM: commitbank_f1: training: 0.048773 validation: 0.054645
08/15 09:27:02 PM: commitbank_precision: training: 0.232253 …
```
=> Fix validation macro and micro average calculations

jiant/modules/seq2seq_decoder.py, jiant/tasks/seq2seq.py
Gold target sequence not needed for seq2seq generation, and only used *during training* if available.
=> Target optional for seq2seq

environment.yml, setup.py
=> update dependencies to support gpt2-large

scripts/taskmaster/transfer_analysis.sh
model_*.th might indicate several models; fixed to model_*.best.th
=> small fix transfer_analysis.sh

jiant/tasks/qa.py
some name was mixed up in the renaming of last PR, hence breaking the commonsense qa task.
=> Fix CommonsenseQA bug

jiant/tasks/__init__.py, jiant/tasks/acceptablity_probing.py, jiant/tasks/nli_probing.py, jiant/trainer.py
git didn't match this one well. the changes in nli_probing in fact is simply replacing nli-prob-negation and nli-prob-prepswap with a unified task class.
=> Function words probing

CODEOWNERS
This makes an approval from Phil sufficient to allow merging without additional approvals.
=> Add Phil to owners.

jiant/__main__.py, jiant/preprocess.py, jiant/utils/config.py, jiant/utils/options.py
This PR adds some docstrings and return value type hints to jiant's setup and preprocessing code. This PR is not expected to change any current jiant logic.
=> Add docstrings and type hints in setup and preprocessing code

jiant/huggingface_transformers_interface/modules.py, jiant/preprocess.py, jiant/tasks/edge_probing.py, jiant/tasks/qa.py, jiant/tasks/tasks.py, jiant/utils/utils.py, tests/test_huggingface_transformers_interface.py, tests/test_preprocess.py
This PR proposes a change to addresses the max_seq_len issue: https://github.com/nyu-mll/jiant/issues/1002. 
These changes were validated on [the example](https://github.com/nyu-mll/jiant/issues/1002#issue-559833991) provided by @zphang. @W4ngatang for visibility.
=> Address max sequence length issue (#1002)

tutorials/setup_tutorial.md
Updates version/tag referenced in setup tutorial to latest release (v1.3.0).
=> Update jiant version references in setup tutorial

cola_inference.py, jiant/models.py, jiant/modules/edge_probing.py, jiant/tasks/edge_probing.py
https://github.com/nyu-mll/jiant/issues/1017
Modifying edge-probing to fit into new update_metrics function signature. There's still a weird error going on with edgeprobing on Multi-GPU so I raised an error.
=> Fixing Edge-Probing after muti-GPU release

tutorials/setup_tutorial.md
Update refs in setup tutorial to v1.3.1 (preparing for a patch release).
=> Update refs in setup tutorial to v1.3.1

README.md
#1067
I'm working on a parallel PR to jiant.info.
=> Backronym "jiant"

jiant/tasks/tasks.py, scripts/download_glue_data.py
Addresses issue #1073. Also, externally will update the download link in `scripts/download_glue_data.py` to move the jsonl data to top-level where the task expects it to be.
=> Switch to jsonl format for SNLI

probing/README.md
Clarify how to compute the coreference metrics from the paper
=> Update probing readme

tutorials/setup_tutorial.md
Re. #1106. @W4ngatang or @iftenney, would mind taking a quick look? We're short on 1.x reviewers.
=> Clarify setup and environment variable instructions

jiant/tasks/lib/scitail.py
This PR closes https://github.com/jiant-dev/jiant/issues/188 and was tested by tokenizing with the simple API.
=> scitail tokenization fix

README.md
Trying to list v2 contributors in rough order of contribution, then v1-only contributors. Not at all sure I got the v2 order right. Suggestions?
=> Proposed citation for v2

README.md
=> Update LICENSE link in README.md

jiant/shared/model_resolution.py, jiant/tasks/lib/templates/span_prediction.py
This PR closes https://github.com/nyu-mll/jiant/issues/1200 when combined with https://github.com/nyu-mll/jiant/pull/1201.
=> resolve_is_lower_case fix

guides/experiments/my_experiment_and_me.md, guides/tutorials/quick_start_main.md, guides/tutorials/quick_start_simple.md, jiant/proj/main/metarunner.py, jiant/proj/main/runscript.py, jiant/proj/simple/runscript.py, jiant/shared/runner.py
This commit makes explicit separate save-best and save-last behaviors, into `best_model.p` and (new) `last_model.p`.
=> Fix save-last behavior

guides/general/in_depth_into.md
Fixed two typos in in_depth_into.md
=> minor typo fix

jiant/proj/main/metarunner.py
https://github.com/nyu-mll/jiant/pull/1220#issuecomment-739452165
=> Use do_save_last

jiant/tasks/lib/wsc.py
=> Fix _create_examples in wsc.py

jiant/proj/main/modeling/primary.py
`model_output` has loss only when `compute_loss` is `True`.
=> Prevents computing loss in multigpu when not available
