config/defaults.conf, probing/split_constituent_data.py, src/tasks.py
Helper script to split constituent data into nonterminals and POS, and configs for these tasks.
TODO to just merge this functionality into the original script that produces the constituent data from OntoNotes. But would prefer to check this in for now since it works, and then streamline things later.
=> Fix split script, add nonterminal & pos tasks

probing/data/README.md, probing/data/get_ud_data.sh, probing/data/ud_to_json.py
Cherry-picked from `edgeprobe_docs` to include the UD code only. Relative to that branch, also refactored argument handing & wrapper script for consistency with other datasets.
=> Edge probing: UD data code & instructions

config/edgeprobe_bare.conf, config/edgeprobe_cove.conf, config/edgeprobe_existing.conf, config/edgeprobe_glove.conf, config/edgeprobe_openai.conf, config/edgeprobe_train.conf
This makes it easier to debug locally, since it'll use an experiment directory
in the user's home directory instead of on NFS. Kubernetes runs are unaffected
since JIANT_PROJECT_PREFIX and NFS_PROJECT_PREFIX are the same in that
environment.
=> Remap edge probing configs to use JIANT_PROJECT_PREFIX

Dockerfile, demo.with_docker.sh
Fix breakages in Dockerfile due to #471, mostly related to different package requirements in the new version of AllenNLP. Verified that `demo.conf` (no overrides) and `edgeprobe_bert.conf` with `target_tasks=edges-spr2,bert_embeddings_mode=cat,bert_model_name=bert-base-uncased` produce identical results (up to random noise) before and after this update. 
_(Note: before tests run using a snapshot before #471 for compatibility with older AllenNLP and PyTorch)_.
=> Update Dockerfile for compatibility with new AllenNLP and PyTorch 1.0

scripts/download_glue_data.py
FB moved their hosting of MRPC to another link so I'm updating download_data_glue.py
=> Fixed MRPC Data Link in download_data_glue

config/defaults.conf
I think this warning was left over from before a big name change. Merge when approved.
=> Remove odd warning in comment.

gcp/kubernetes/run_batch.sh
GCP now adds a taint to GPU nodes to prevent non-GPU pods from scheduling on
them, so we need to add an explicit toleration to handle this.
=> Add toleration to k8s pod config for new GPU nodes

config/defaults.conf, src/models.py, src/modules/modules.py, src/modules/seq2seq_decoder.py
Remove pooler `from_params` attribute because it really wasn't that hard to just use the normal constructor and it didn't expose the `pool_type` arg (relevant for BERT).
Refactor pair sentence attention constructor because it was weird.
=> Remove pooler from_params attribute + refactor pair sentence attention

src/preprocess.py, src/tasks/__init__.py, src/tasks/lm.py, src/tasks/mt.py, src/tasks/nli_probing.py, src/tasks/reddit.py, src/tasks/tasks.py
Includes
* Make all tasks use `task._tokenizer_name` when processing data
* Remove removed usage of SOS/EOS tokens in calling `process_sentence`
* Create WikiText 2 skipthought task (mainly for debugging)
* Update comments
* Update some paths
=> Add tokenizer names to various tasks

config/defaults.conf, main.py
Add ability to fine-tune entire model. PR includes:
- wrap checkpoint searching in a function in main to avoid code duplication during target task evaluation
- create a pre-target-task-training checkpoint if no pretraining
- during target task training, get all model parameters and save the resulting model checkpoint in a target-task-specific checkpoint
- during target task evaluation, load the correct target-task-specific fine-tuned model (and use MNLI for MNLI diagnostic)
=> Add fine-tuning of entire model

src/tasks/tasks.py
Some of the tasks still had errors when loading the data from scratch due to old parameter names in `load_tsv`. This PR fixes that.
* `targ_map` -> `label_fn=targ_map.__getitem__`
* add `label_fn=int` in QQP.
=> Add fixes for loading QNLI, RTE

probing/retokenize_edge_data.py, src/utils/retokenize.py
Changes:
Extracting out tokenization alignment functions from probing/ to src/utils/retokenize.py. This will allow non-probing tasks to also use these tokenization alignment methods.
=> Extracting out tokenization alignment functions

src/models.py, src/tasks/mt.py, src/tasks/reddit.py, src/tasks/tasks.py
Refactoring scorers to make it more flexible. 
Changes: 
-> Added update_metrics to Task class to allow for flexibility in scorers (moving that logic out of src/models.py to individual tasks) 
-> Added self.subset_scorers to tasks to fit API 
Currently only affects single single sentence tasks and pair sentence classification tasks (non-diagnostic)
Current status:
-Tested on WNLI, STSB, COLA
-Testing on the rest of the affected tasks
=> Refactoring scorer + update_metrics

src/modules/modules.py
Fix a typo in modules.py (`task_sent_embs` -> `sent_embs`)
=> Fix typo in modules.py

scripts/download_glue_data.py
Right now, the snli cleanup writes all of the training examples to a single line. I added one line to take care of the fix. Thanks!
=> bugfix: snli processing

main.py
Move where we create the untrained checkpoint (for referring back to when fine-tuning on multiple target tasks w/o pretraining).
=> Fix order of checkpointing to not create extra checkpoint

src/modules/seq2seq_decoder.py
Our beam search implementation was never complete and bug free. It's mostly gone, but I'm getting rid of one last bit of unsupported code here.
=> Remove the last vestige of beam search

config/defaults.conf, config/edgeprobe_existing.conf, main.py, src/models.py
Previously, we used `is_probing_task` and `get_task_whitelist` to load tasks (e.g. MNLI) whose classifier we are using for another task (e.g. some probing task), but we don't want to train on the source task (e.g. because we have a pretrained model). No task actually uses this option now, so let's drop it. This means that if you want to use task A's classifier for task B, you must load task A and task B (and either train on it or do it in two runs).
addresses issue #372
=> Remove `is_probing_task` flag

config/defaults.conf
Deals with #631 by removing dead pool_type option. If important later, we can expose this again. Will use max pooling for everything except BERT, where we use "first" pooling
=> Remove pool type logic

main.py, src/models.py, src/utils/config.py, src/utils/utils.py, tests/test_logging_utils.py
This removes extra logging from #602 , more specifically:
-A lot of the 1-line logs (easy case). 
-The unrelated parameter arguments that were being printed out. Here, we use union of (a diff between the experiment configurations and defaults.conf) and task-specific parameters for tasks used in the experiments 
Now, after this change, the log for the parameters for demo.conf are as below:
{
"batch_size": 8,
"classifier_hid_dim": 32,
"d_word": 50,
"exp_dir": "coreference_exp/jiant-demo/",
"exp_name": "jiant-demo",
"load_model": 0,
"local_log_path": "coreference_exp/jiant-demo/new_5/log.log",
"max_seq_len": 10,
"max_vals": 10,
"max_word_v_size": 1000,
"mrpc": {
"classifier_dropout": 0.1,
"classifier_hid_dim": 256,
"max_vals": 8,
"val_interval": 1
},
"mrpc_classifier_dropout": 0.2, …
=> Remove extra logging (jiant-side)

src/tasks/tasks.py
Fixing the relative path that the src/tasks/tasks reads from to match the directory the downloader downloads CB data to. 
Fix for  #713
=> Fixing CommitmentBank Relative Path

config/defaults.conf, main.py
There are other bigger issues to fix, but here are a few easy improvements:
- Allow wildcards in 'load_target_train_checkpoint', for the common case where you want to use the best pretraining epoch from some other run, but you don't know in advance which epoch that'll be.
- Fix some logic that breaks when restoring fine-tuning jobs.
- A bit more cleanup/commenting.
=> A few easy checkpointing logic fixes.

src/evaluate.py, src/trainer.py
This stops storing intermediate state during eval-mode computations, which saves some time/memory. @zphang already does this in the standalone eval script, and it's recommended here: 
https://discuss.pytorch.org/t/torch-no-grad/12296
=> torch.no_grad() when evaluating.

main.py, src/trainer.py, tests/test_checkpointing.py, tutorials/setup_tutorial.md
Changes:
In target task training, we no longer keep only one checkpoint path - instead, for each target task, we store in separate directories. This applies to both transfer_paradigm=frozen and finetune. 
For pretraining, we still save the checkpoints in the run_dir directory - pretraining checkpoints should not be affected by this PR.
=> Adding Separate Best Checkpoints for Target Train tasks

tutorials/setup_tutorial.md
This matches what's done in Dockerfile in specifying a target directory, and seems to be more robust. Should fix #744.
=> Update to ntlk download instructions

src/tasks/tasks.py
Meant to fix the second half of #773.
I'm not sure if this is necessary—it may be safe to just delete this entirely and trust that PyTorch will move this over when it moves over the rest of the model. In any case, though, raw cuda() calls break CPU machine support. 
@pruksmhc, you wrote this part—any ideas?
=> WSC cuda fix

src/tasks/tasks.py
In the current version of WSC, the labels were being switched ("False"in the dataset was being mapped to 1, and "True" to 0). This PR fixes it.
=> Fixing labels for WSC

config/defaults.conf, src/trainer.py, tests/test_checkpointing.py
Delete mentions of "warmup". Note that there's still one mention relevant to the BERT optimizer that we don't expose as an option.
Relevant to #598
=> Remove Transformer training warmup option

src/tasks/tasks.py
My assumption+assert that in WiC processing, the start of the marked word should (string) match the processed tokens is incorrect because some tokenizers (Moses) change some characters ( "'" -> &apos;). This breaks the assert.
=> Remove buggy assert in WiC

jiant/evaluate.py, jiant/modules/span_modules.py, jiant/tasks/tasks.py, jiant/utils/data_loaders.py, scripts/download_superglue_data.py
Currently, WSC labels are being loaded via the get_all_labels() function, which is mapping the labels to integers. However, this is causing complications when running a non-WSC baseline, followed by the WSC baseline, due to some naming errors. 
Here, we implement a more standard flow for preprocesisng abels.
=> Fix wsc labels

jiant/tasks/tasks.py
Addresses #836 by swapping `sent1[:-1] + sent2` -> `sent1 + sent2[1:]`.
=> Fix bug in BERT preprocessing

jiant/tasks/edge_probing.py
Fix a crash on task.get_all_labels() (due to a bad merge?), and fix data paths to match probing/get_and_process_all_data.sh.
TODOs:
- Verify numbers match the paper
- Clean up old tasks and unused code paths
- Get Kubernetes working
=> Fix edge probing at head

Dockerfile, environment.yml, gcp/kubernetes/templates/jiant_env.libsonnet, gcp/kubernetes/templates/run_batch.jsonnet, scripts/demo.with_docker.sh
Instead of installing individual packages, just use conda environments inside the Docker image to keep versions synchronized with non-Docker usage.
Also, remove hard-coded paths from the Dockerfile. For local runs you can pass these with -e, and for Kubernetes these are defined in `jiant_env.libsonnet` and handled appropriately in the job YAML files.
Kubernetes run scripts should behave identically as before, unless you were doing something weird with environment vars.
=> Use environment.yml in Dockerfile

gcp/kubernetes/run_batch.sh, gcp/kubernetes/templates/jiant_env.libsonnet
Better default behavior on a multi-user cluster.
=> Add username to job name and project dir for Kubernetes runs

jiant/preprocess.py, jiant/pytorch_transformers_interface/modules.py, jiant/tasks/tasks.py
1. When task includes index pointing to a certain location in the input, the index is not adjusted w.r.t. the boundary function. So every input module from pytorch_transformer is not acting correctly on WiC.  And XLNet is not working correctly for WSC. Blimp & NPI pair do not suffer from the problem though. I added optional outputs that return the index offset when applying boundary tokens to sentences, so the index is correct now.
2. Huggingface fixed their vocab file problem, so I remove the code coping with that problem.
3. I found there were some tailing spaces in the docstrings of pytorch_transformers_interface, so I removed them.
=> Fixing index problem & minor pytorch_transformers_interface cleanup

jiant/pytorch_transformers_interface/modules.py
Previously, pytorch_transformers_interface uses inplace operation to adjust token index, this can cause problem when sent_enc is not "none".
=> replace correct_sent_indexing with non inplace version

probing/README.md
Thanks to #936, we've discovered errors in our data statistics reporting in the edge probing paper. This table contains the corrected values. As there is more space here, the full (unrounded) values are reported instead. This was generated by a script that read the stats.tsv file and the diff vs. the paper should match my comment on the issue yesterday.
=> Add corrected data statistics

jiant/pytorch_transformers_interface/modules.py
Currently the `_unk_id` for Roberta is not set correctly, which triggers the assertion error on line 118.
=> Set _unk_id in Roberta module

jiant/__main__.py
In the current version of jiant, load_target_train_checkpoint was not working in the "mix" setting.  This is a fix for that.
=> Fixing load_target_train_checkpoint with mixing setting

environment.yml
- Bump `pytorch` requirement to `1.1.0` for compatibility w/ [XLNet implementation](https://github.com/huggingface/transformers/issues/1122)
- Bump `numpy` requirement to `1.15.0` for compatibility with our `spacy==2.1` requirement
=> Update pytorch and numpy version requirements

jiant/tasks/tasks.py
Hi — here's an implementation of a jiant task for [Adversarial NLI](https://arxiv.org/abs/1910.14599).
I'm proving out a refactor in `task.py`, but in the meantime here's a (rather doc-verbose) implementation based on other similar jiant tasks.
Test performance for jiant vs. the ANLI paper with similar configs:
- jiant Adversarial NLI task: (w/ bert-large-cased) validation accuracy = 50.8%
- Adversarial NLI paper:  (w/ bert-large) test accuracy = 50.5%
=> Adversarial NLI Task

jiant/metrics/nli_metrics.py, jiant/tasks/tasks.py, tests/test_nli_metric.py
This adds the option to train a model on the three-class MNLI dataset and evaluate it on comparable two-class datasets like RTE or HANS. It does this by overriding the usual accuracy metric with an NLI-specific accuracy metric that collapses 'neutral' and 'contradiction'.
=> Add a two-class variant of the MNLI task

.circleci/config.yml
Currently, our pre-commit hook targets a specific version of the `black` Python style checker/fixer, but our CircleCI test tool automatically downloads the latest version. As of now, the latest version is substantially different from the version we target, so there can be cases where the automatic pre-commit style fix actually causes the code to fail the CircleCI style check. 
See, for example: https://circleci.com/workflow-run/502bba6a-1ffc-4845-83df-58094be11d4a?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification 
This change tells CircleCI to use the same fixed version we use locally for pre-commit. (This seems pretty clearly better than using the latest version in both places, as that could easily introduce confusing transient failures after new versions of `black` …
=> Specify version of black for CircleCI

README.md, jiant/__main__.py, jiant/config/defaults.conf, jiant/trainer.py, tests/test_checkpointing.py, tests/test_gradient_accumulation.py
This PR adds gradient accumulation as a training option. Gradient accumulation allows us to increase the effective batch size (and use a wider range of GPUs for experiments).
We validated these changes on ReCoRD and BoolQ tasks where we confirmed that we can use gradient accumulation and smaller batch sizes to match the performance of larger batch sizes.
=> Add gradient accumulation as an option

jiant/trainer.py
Currently, in `trainer.py`, in method `_setup_training`, a `task_info` dict is created for each task, and an optimizer and a scheduler is initialized and stored in each `task_info` dict. However, I don't see any further access to `optimizer` or `scheduler` fields in `task_info` dicts. 
This PR proposes removing the code in `_setup_training` that initializes and stores optimizer and scheduler objects in `task_info` dicts.
=> Remove code initializing optimizer and scheduler fields in task_info

jiant/trainer.py
This PR cleans up a couple items in `jiant/trainer.py`:
1. a6fef61 changes the name of `task_info`'s "loss" field (which really tracks loss _since last val_ because it is reset as a side effect of calling `_validate`) to "loss_since_val".
2. There are a number of places in `SamplingMultiTaskTrainer` where a local var in a method is set to reference a field of the class. These extra variables / points of access can get confusing. 1cc7f6e and 37d6b32 make changes to access the member fields directly.
3. 7f72e96 makes changes to access dict values directly (instead of through extra local vars).
=> Cleanup/readability changes in trainer.py

jiant/trainer.py, jiant/utils/utils.py
This change makes loss metrics under different GPU configs more consistent by computing the average loss (instead of sum) across GPUs:
* 4b920c6 adds 'mean' as a reduction type option to `get_output_attribute` (the fn used to reduce scalars gathered in the output dict during DataParallel training). 
* 07a3b15 switches the `loss` calculation under DataParallel training to use 'mean' (instead of 'sum') as its reduction fn.
=> Use mean as reduction method for loss with DataParallel training

jiant/models.py
Conversion of the [sorted tasks list](https://github.com/nyu-mll/jiant/blob/3ecea5584cd179588314451aaf515dd7922232ad/jiant/__main__.py#L516) to an [unordered set in build_task_modules](https://github.com/nyu-mll/jiant/blob/3ecea5584cd179588314451aaf515dd7922232ad/jiant/models.py#L500) is a source of variation in outputs on runs with the same configs (for example, see logs for "running demo.sh" on builds [1772](https://circleci.com/gh/nyu-mll/jiant/1772?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) and [1776](https://circleci.com/gh/nyu-mll/jiant/1776?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)). This change maintains a sorted order for `tasks` making it easier to reproduce runs.
=> Minor change to maintain sorted order of tasks to reduce variation in logs

jiant/__main__.py, jiant/preprocess.py
Simple fix for https://github.com/nyu-mll/jiant/issues/1000: "wrong error description when both pretrain and target tasks are empty".
Previously, error read: `Error: mixing tasks with different tokenizers! Tokenizations`.
Error now reads: `Error: Must specify at least one pretraining task`, or `Error: Must specify at least one target task`. 
These changes continue to handle the case where task args are set to string "none", as demonstrated in [these configs](https://github.com/search?q=%22pretrain_tasks+%3D+none%22&type=Code).
=> Fix "wrong error description when both pretrain and target tasks are empty"

jiant/tasks/tasks.py
Project-wide search turned up no uses of the `tokenizer_is_supported` method.
This is a bite-size PR to remove this unused method from the tasks.
Possible review strategy: verify that these methods aren't called.
=> Remove unused method of Task classes: tokenizer_is_supported

jiant/evaluate.py, jiant/trainer.py
This PR patches issue #1011, "Micro average logged as 0.000 for some tasks":
1. 84729e8 removes an instance of double counting of `n_exs` in validation metric calc
2. 23dad18 extracts n_exs differently w/ single- and multi-GPUs (single -> int, multi -> tensor)
These changes were validated on the `commitbank` task in single- and multi-GPU modes.
These changes were not validated across the whole set of tasks/benchmarks used in [#992](https://github.com/nyu-mll/jiant/pull/992#issuecomment-588256306).
=> Patch to fix micro average calculation under DataParallel

jiant/preprocess.py, jiant/tasks/qa.py, jiant/tasks/tasks.py
This PR is a refactor that updates the `QASRLTask` class to use consistent data field names with all the other tasks (57d1912), and with b9b41bb it removes an unnecessary attempt to free up memory during preprocessing (unnecessary because in all tasks except `QASRLTask` pre-57d1912 these fields aren't populated at this stage of the preprocessing pipeline).
=> Minor refactor for task structure consistency and clean up in preprocessing

jiant/huggingface_transformers_interface/modules.py, jiant/preprocess.py, jiant/tasks/edge_probing.py, jiant/tasks/qa.py, jiant/tasks/tasks.py, jiant/utils/utils.py, tests/test_huggingface_transformers_interface.py, tests/test_preprocess.py
Final pre-release validations found inconsistencies in whether `s1` or `s2` contained the candidate for truncation. This PR reverts PR nyu-mll/jiant#1006, and issue #1002 remains open to track work on a fix.
=> Revert "Address max sequence length issue (#1002)"

jiant/tasks/qa.py
Issue #1018 points out that QAMR and QASRL throw `AttributeError` on access to Task data fields (these fields were modified in PR #1004). This PR fixes `get_split_text`'s access to these fields.
The changes in this PR were validated by starting training w/ QAMR and QASRL tasks (w/o failure).
@HaokunLiu — for visibility as author of issue #1018.
=> Address issue #1018: QAMR and QASRL throw `AttributeError`

README.md
Author ordering roughly follows commit/PR/deletion statistics from GitHub. The intent is to recognize 1.3 as a mix of the old JSALT/GLUE code and the new cleaner Transformers-centric push. (Presumably this will change further in 1.4+.)
=> Update author list

jiant/models.py, jiant/modules/edge_probing.py, jiant/tasks/edge_probing.py
This PR builds on #1025 "Fixing Edge-Probing after muti-GPU release".
**Important notes:**
1. w/ these changes `forward()` won't put `n_inputs` into model `out`. `n_inputs` does not appear to be accessed in the project, and leaving it in would require special handling for multi-GPU. 
2. the prediction processing functionality from `unbind_predictions` (a method of the edge probing module) is being moved to the `EdgeProbingTask`'s `handle_preds` method (a method of the parent `Task` for "task-specific processing of predictions",  introduced w/ #992).
=> WIP: Extend edge probing fix to run in multi-GPU mode

jiant/tasks/tasks.py
When discussion with Phil about the preprocess function, I found I wrote a typo when implementing the preprocessing of gpt2-like single directional model.
This will have slight negatively affect on the performance of gpt, gpt2 and transformer-xl on sts-b, mrpc, qqp. But not other transformer models or other tasks.
=> fix mirrored pair input

CONTRIBUTING.md, README.md
Adds test and documentation guidelines to `CONTRIBUTING.md`, and removes redundant contributing guidelines from `README.md`.
=> Add test and documentation guidelines to CONTRIBUTING.md

README.md
Fixes broken FastText link in README (issue #939).
=> Fix FastText link in README

jiant/trainer.py
Now target_train_data_fraction will correctly affect the number of training examples in trainer, and logging and scheduler that depend on it. 
We will need this merged before running the 5k probing tasks in taskmaster.
=> Fix number of training examples in target training

tutorials/setup_tutorial.md
PR bumping version of jiant in setup instructions (preparing for v1.3.2 release).
=> Update refs in setup tutorial to v1.3.2

jiant/trainer.py
Addresses https://github.com/nyu-mll/jiant/issues/658 by temporarily increasing (and then restoring) the log level around [this code](https://github.com/nyu-mll/jiant/blob/master/jiant/trainer.py#L510-L513) from `INFO` to `WARNING` (`WARNING` is the level above `INFO`, and warnings will still be logged).
=> Suppress verbose INFO-level logging by AllenNLP components in trainer.py

setup.py
This PR addresses issue #1088. For background on the issue, see issue #1088.
=> Pin sklearn version in setup.py for compatibility with allennlp==0.8.4

jiant/utils/data_loaders.py
This PR is motivated by issue #1082 (please see that issue for important context).
This PR would change the behavior of `load_tsv()`: if pandas finds a "bad line" in the data passed to `load_tsv()`, a `pandas.errors.ParserError` will be thrown and the run will stop.
**How was this PR validated/tested?** For all tasks where I had task data on hand (10+ tasks including SNLI), on this PR branch (i.e., w/ `error_bad_lines=True`) I ran code to trigger a call to `load_tsv()`, and for all tasks except SNLI `load_tsv()` worked without an exception. For SNLI (where [we know there's some inconsistency](https://github.com/nyu-mll/jiant/issues/1073) in the format of the data file) this (expected) exception is raised:
```
pandas.errors.ParserError: Error tokenizing data. C error: Expected 11 fields in …
```
=> Update load_tsv to stop if "bad lines" are found

scripts/download_glue_data.py
We are in the process of update the download URLs of GLUE to FB hosted data files. This change updates the link in glue data download script.
Test Plan:
Locally verified that the script is working.
=> [fix] Update the glue data script to use new download links

jiant/tasks/lib/wsc.py
This PR closes https://github.com/jiant-dev/jiant/issues/190 and fixes tokenization errors introduced when switching to `datasets` for task downloading. `datasets` has a slightly different format for the wsc task.
This PR was tested by successfully tokenizing the data with the simple API.
=> WSC tokenization fix

README.md
Related: Make sure that links within the v1-legacy repo are correct. (i.e., they don't use hard-coded `nyu-mll/jiant` anywhere).
=> Removing potentially confusing paper details.

jiant/proj/main/modeling/model_setup.py
Just for consistency - this should not affect the logic.
=> Use hidden_size in taskmodels

examples/notebooks/jiant_Basic_Example.ipynb, examples/notebooks/jiant_MNLI_Diagnostic_Example.ipynb, examples/notebooks/jiant_Multi_Task_Example.ipynb, examples/notebooks/jiant_STILTs_Example.ipynb, examples/notebooks/jiant_XNLI_Example.ipynb, examples/notebooks/simple_api_fine_tuning.ipynb
This PR updates the example notebooks to point at the `nyu-mll/jiant` 2.0.0 release.
=> Fix git clone in example notebooks 

jiant/tasks/lib/arc_challenge.py, jiant/tasks/lib/arc_easy.py
This PR fixes a tokenization issue for `arc_easy` and `arc_challenge` datasets. It seems there are some changes in format when using `datasets`. Tested and ran successfully with `roberta-large` using the following command:
```
python ${JIANT_PATH}/proj/main/tokenize_and_cache.py \
--task_config_path ${DATA_DIR}/configs/${TASK_NAME}_config.json \
--model_type ${MODEL_NAME} \
--model_tokenizer_path ${MODELS_DIR}/${MODEL_NAME}/tokenizer \
--phases train,val,test \
--max_seq_length 256 \
--do_iter \
--smart_truncate \
--output_dir ${CACHE_DIR}/${MODEL_NAME}/${TASK_NAME}
```
=> Fix tokenization for arc_easy and arc_challenge

jiant/proj/main/components/container_setup.py
There are two sources of task names in `jiant`.
1. The task-names provided in the `task_name`->`task` mapping from the `task_config_dict`
2. The `task.name`, which is derived from the task config.
In all parts of the `jiant` training/eval loop, we use `task_name`, including for creating the models. The one exception is the runner calling the model, where we use the task object (and hence `task.name`).
To resolve this conflict, we will assign the `task.name = task_name` and throw a warning if they do not agree.
=> use task_name instead of task.name

guides/tasks/adding_tasks.md, guides/tasks/supported_tasks.md, jiant/scripts/download_data/constants.py, jiant/scripts/download_data/runscript.py, jiant/tasks/constants.py, jiant/tasks/lib/mcscript.py
This PR adds documentation for:
1. Adding a task to the data downloader (now required when adding a task)
2. @ the creator of a task when opening a PR adding a task
=> Add docs for adding tasks to data downloader

jiant/scripts/download_data/dl_datasets/files_tasks.py, jiant/tasks/lib/templates/squad_style/core.py
1. Fixes SQuAD v2 task config to properly supply kwargs
2. Update SQuAD tokenization logic based on https://github.com/huggingface/transformers/pull/7387 (and subsequently refactored in https://github.com/huggingface/transformers/pull/7970)
The summary for 2 is that previously (including in the Hugging Face implementation), the context was being tokenized per-word rather than as a string. This is problematic for tokenizers that treat start-of-word tokens differently. 
Although the cited PR states that there is a large performance improvement from this fix, I did not observe this myself in my testing (both in `jiant` as well as in the `transformers` examples). Both versions appeared to perform comparably.
For `jiant` users, this will impact tokenization, but training a fresh model for …
=> SQuAD update

guides/tutorials/quick_start_main.md, jiant/proj/main/runscript.py, jiant/proj/simple/runscript.py
This PR closes #1198 by deleting the checkpoint at the end of training by default.
=> Change checkpoint save default behavior

jiant/proj/main/modeling/model_setup.py
#1193
I also found that loading only encoder weights (and randomly initializing the task heads), because of the final learned representation, it is not uncommon even for randomly initialized task heads to have very strong task performance.
=> Load only encoder weights

jiant/proj/main/modeling/model_setup.py
Handles cases of loading across different taskmodel configurations
=> Further fix for encoder_only

jiant/proj/simple/runscript.py
The default cache directory should be namespaced by model-type so that when 2 different models are sequentially run on the same task, the latter doesn't use cached inputs from previous model.
=> Namespace default cache dir by model_type.

jiant/proj/main/metarunner.py, jiant/utils/torch_utils.py, tests/proj/simple/test_runscript.py
This PR closes https://github.com/nyu-mll/jiant/issues/1222 by adding save model tests for the simple runscript. These tests check the model saving behavior by:
1. Overfitting a model and checking the last model weights are different than the best model weights
2. Checking that only the best model is saved with the `do_save_best` argument.
3. Checking that only the last model is saved with the `do_save_last` argument.
This PR also corrects a small bug in saving behavior (required for the tests to pass).
=> Add simple save model test

jiant/proj/main/modeling/primary.py, jiant/proj/main/modeling/taskmodels.py, jiant/proj/simple/runscript.py, requirements-no-torch.txt, setup.py, tests/proj/simple/test_runscript.py
These changes move the if-else statements (for `ModelArchitectures`) in `get_output_from_encoder()` to the newly added `JiantTransformersModel` when using `__call__`.
=> Refactor get_output_from_encoder() to be member of JiantTaskModel

tests/tasks/lib/templates/test_hacky_tokenization_matching.py
Adds tests for `flat_strip()` as requested at https://github.com/nyu-mll/jiant/pull/1288#discussion_r588938075
=> Add tests for flat_strip()

jiant/proj/main/modeling/model_setup.py, jiant/proj/main/modeling/primary.py, jiant/proj/main/modeling/taskmodels.py, jiant/proj/main/tokenize_and_cache.py, jiant/shared/model_resolution.py, jiant/tasks/lib/ccg.py, jiant/tasks/lib/templates/hacky_tokenization_matching.py, tests/tasks/lib/templates/test_hacky_tokenization_matching.py, tests/tasks/lib/test_mlm_premasked.py, tests/tasks/lib/test_mlm_pretokenized.py, tests/tasks/lib/test_mnli.py, tests/tasks/lib/test_spr1.py
This PR refactors the following:
- adds getter for mlm_weights_dict to `JiantTransformersModel`
- add  getter for feat_spec to `JiantTransformersModel`
- simplifies `flat_strip()`
=> mlm_weights(), feat_spec(), flat_strip() if-else refactors

jiant/proj/main/modeling/primary.py, jiant/shared/model_resolution.py, jiant/utils/python/datastructures.py, jiant/utils/tokenization_normalization.py, jiant/utils/tokenization_utils.py, tests/utils/test_tokenization_normalization.py
This PR refactors `normalize_tokenizations()` by moving the functions to `JiantTransformerModel`s. Although the location of this logic is not ideal, it was the easiest way to have a central location for editing new models/tokenizers. This PR also adds `resolve_model_arch_tokenizer(tokenizer)` to map the tokenizers to model_archs.
=> Move tokenization logic to central JiantModelTransformers method

jiant/proj/main/components/container_setup.py, jiant/proj/main/modeling/model_setup.py, jiant/proj/main/tokenize_and_cache.py, jiant/proj/simple/runscript.py, jiant/tasks/__init__.py, jiant/tasks/evaluate/core.py, tests/proj/main/test_export_model.py, tests/tasks/lib/test_mlm_premasked.py, tests/tasks/lib/test_mlm_pretokenized.py, tests/tasks/lib/test_mnli.py, tests/tasks/lib/test_spr1.py, tests/tasks/lib/test_sst.py, tests/utils/test_tokenization_normalization.py
Importing `BatchMixin` in primary previously imported all tasks resulting in a circular import with `tokenization_normalization()`. This PR fixes the circular imports by removing `import *` in tasks `__init__.py`.
=> Fix tasks circular import

jiant/proj/simple/runscript.py
Running the simple runscript with a task that does not have datasets for all the three phases (train/test/val) results in error. E.g., the following command:
```
python jiant/proj/simple/runscript.py run --run_name simple --exp_dir ${EXP_DIR}/ --data_dir ${EXP_DIR}/tasks --hf_pretrained_model_name_or_path roberta-base --tasks squad_v1 --train_batch_size 16 --num_train_epochs 3
```
results in the following error:
```
File "jiant/proj/simple/runscript.py", line 267, in <module>
main()
File "jiant/proj/simple/runscript.py", line 259, in main
run_simple(args, with_continue=False)
File "jiant/proj/simple/runscript.py", line 151, in run_simple
tokenize_and_cache.main(
File "jiant/proj/main/tokenize_and_cache.py", line 203, in main
examples=task.get_test_examples(),
File …
```
=> improve robustness of the simple runscript

jiant/proj/simple/runscript.py
This is a fix for #1348.
While the tokenization etc is still cached for each model type, now multiple models can be run for the same model type, for example caching for `roberta` while both `roberta-base` and `roberta-large` can be run.
=> Bugfix for simple_run() multiple models with the same type.
